# This file was generated by GoReleaser. DO NOT EDIT.
cask "indev" do
  name "indev"
  desc "A CLI for managing developer platform resources."
  homepage "https://developers.intility.com"
  version "0.9.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "indev"
  bash_completion "completions/indev.bash"
  zsh_completion "completions/indev.zsh"
  fish_completion "completions/indev.fish"

  on_macos do
    on_intel do
      url "https://github.com/intility/indev/releases/download/v#{version}/indev_darwin_x86_64.tar.gz",
        header: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["DOWNLOADER_GITHUB_TOKEN"]}",
        ]
      sha256 "84c59978a20b3801cd7fb577693e6f61703f4514034e5d42ff7339c3e82abd4b"
    end
    on_arm do
      url "https://github.com/intility/indev/releases/download/v#{version}/indev_darwin_arm64.tar.gz",
        header: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["DOWNLOADER_GITHUB_TOKEN"]}",
        ]
      sha256 "4f6747f1c6fa4740a8e4e2788bca0cd0800872566c757ca4f7462b52ad60dae0"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/intility/indev/releases/download/v#{version}/indev_linux_x86_64.tar.gz",
        header: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["DOWNLOADER_GITHUB_TOKEN"]}",
        ]
      sha256 "7cd026a25db3a2a31de009d5e6dfd577c424c65aa4921b6df9858c6a975e1c03"
    end
    on_arm do
      url "https://github.com/intility/indev/releases/download/v#{version}/indev_linux_arm64.tar.gz",
        header: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["DOWNLOADER_GITHUB_TOKEN"]}",
        ]
      sha256 "1e3fd4ba9cdf079721f6724fe44e62ca073d7b657c2c2077d63db6faaab0deeb"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/indev"]
    end
  end

  # No zap stanza required
end
