# This file was generated by GoReleaser. DO NOT EDIT.
cask "indev" do
  version "1.4.0"

  on_macos do
    on_intel do
      sha256 "8f9423924c788843738920d38eacccd65cc06e187df769727d5b9c951b08beb8"
      url "https://github.com/intility/indev/releases/download/v#{version}/indev_darwin_x86_64.tar.gz",
        header: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["DOWNLOADER_GITHUB_TOKEN"]}",
        ]
    end
    on_arm do
      sha256 "cb919f739dd579cd4772a5e0c5537af7b2d317da1e4835be6f3d3b14c8dd9374"
      url "https://github.com/intility/indev/releases/download/v#{version}/indev_darwin_arm64.tar.gz",
        header: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["DOWNLOADER_GITHUB_TOKEN"]}",
        ]
    end
  end

  on_linux do
    on_intel do
      sha256 "f249db717d0d3d53ae3d5cb7d9c95a03cdc3b511878fad9c38c7047b9701889b"
      url "https://github.com/intility/indev/releases/download/v#{version}/indev_linux_x86_64.tar.gz",
        header: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["DOWNLOADER_GITHUB_TOKEN"]}",
        ]
    end
    on_arm do
      sha256 "84d86f72d65194043ebb4bc70cc0964d05ad3f3751c1f9442a0d66c45143fff9"
      url "https://github.com/intility/indev/releases/download/v#{version}/indev_linux_arm64.tar.gz",
        header: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["DOWNLOADER_GITHUB_TOKEN"]}",
        ]
    end
  end

  name "indev"
  desc "A CLI for managing developer platform resources."
  homepage "https://developers.intility.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "indev"
  bash_completion "completions/indev.bash"
  fish_completion "completions/indev.fish"
  zsh_completion "completions/indev.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/indev"]
    end
  end

  # No zap stanza required

end
