# This file was generated by GoReleaser. DO NOT EDIT.
cask "indev" do
  version "1.6.1"

  on_macos do
    on_arm do
      sha256 "df2d168a242826e9118f837353891981081c0010a8ee80b2f0770384374ba381"
      url "https://github.com/intility/indev/releases/download/v#{version}/indev_darwin_arm64.tar.gz",
        header: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["DOWNLOADER_GITHUB_TOKEN"]}",
        ]
    end
    on_intel do
      sha256 "4428f38fe6bfdf9cfb12965ec1e2b34baf363688a9ac1147b5486aa6b3a26ade"
      url "https://github.com/intility/indev/releases/download/v#{version}/indev_darwin_x86_64.tar.gz",
        header: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["DOWNLOADER_GITHUB_TOKEN"]}",
        ]
    end
  end
  on_linux do
    on_arm do
      sha256 "8bfd0e7495909fe2e5e1e0d11834e4ad4a1ef995cfcb1743cfe699b5aee6051e"
      url "https://github.com/intility/indev/releases/download/v#{version}/indev_linux_arm64.tar.gz",
        header: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["DOWNLOADER_GITHUB_TOKEN"]}",
        ]
    end
    on_intel do
      sha256 "27d227901034e2267b393ba018e61a017efccb21acca7992403887d749c78d02"
      url "https://github.com/intility/indev/releases/download/v#{version}/indev_linux_x86_64.tar.gz",
        header: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["DOWNLOADER_GITHUB_TOKEN"]}",
        ]
    end
  end

  name "indev"
  desc "A command-line interface to Intility Build."
  homepage "https://developers.intility.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "indev"
  bash_completion "completions/indev.bash"
  fish_completion "completions/indev.fish"
  zsh_completion "completions/indev.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/indev"]
    end
  end

  # No zap stanza required
end
