# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Indev < Formula
  desc "A CLI for managing developer platform resources."
  homepage "https://developers.intility.com"
  version "0.4.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/intility/indev/releases/download/v0.4.1/indev_darwin_x86_64.tar.gz",
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["DOWNLOADER_GITHUB_TOKEN"]}"
        ]
      sha256 "d7b0ac699d3e2ece962135a5faac56cf2aed27fb5c76066f443299dc5d603e2f"

      def install
        bin.install "indev"
        bash_completion.install "completions/indev.bash" => "indev"
        zsh_completion.install "completions/indev.zsh" => "_indev"
        fish_completion.install "completions/indev.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/intility/indev/releases/download/v0.4.1/indev_darwin_arm64.tar.gz",
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["DOWNLOADER_GITHUB_TOKEN"]}"
        ]
      sha256 "05c0d76d6994c506e2e4d8dba838867d4ad2742f1bfa2f77563bc3bdcda8d38b"

      def install
        bin.install "indev"
        bash_completion.install "completions/indev.bash" => "indev"
        zsh_completion.install "completions/indev.zsh" => "_indev"
        fish_completion.install "completions/indev.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/intility/indev/releases/download/v0.4.1/indev_linux_x86_64.tar.gz",
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["DOWNLOADER_GITHUB_TOKEN"]}"
        ]
      sha256 "7904759d437197c0ecf9846eced478b30335fe31222a4837db97a8529aad7f34"
      def install
        bin.install "indev"
        bash_completion.install "completions/indev.bash" => "indev"
        zsh_completion.install "completions/indev.zsh" => "_indev"
        fish_completion.install "completions/indev.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/intility/indev/releases/download/v0.4.1/indev_linux_arm64.tar.gz",
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["DOWNLOADER_GITHUB_TOKEN"]}"
        ]
      sha256 "fceda2cbe287216eebb2c72bb5a342df6202ba6d90bb1a269c2dd797299a2e1c"
      def install
        bin.install "indev"
        bash_completion.install "completions/indev.bash" => "indev"
        zsh_completion.install "completions/indev.zsh" => "_indev"
        fish_completion.install "completions/indev.fish"
      end
    end
  end
end
