# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Indev < Formula
  desc "A CLI for managing developer platform resources."
  homepage "https://developers.intility.com"
  version "0.4.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/intility/indev/releases/download/v0.4.0/indev_darwin_x86_64.tar.gz",
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["DOWNLOADER_GITHUB_TOKEN"]}"
        ]
      sha256 "e6d237baca56114e991abda6528d21a8845a463d0f42cd049a6159b8c0c0f33f"

      def install
        bin.install "indev"
        bash_completion.install "completions/indev.bash" => "indev"
        zsh_completion.install "completions/indev.zsh" => "_indev"
        fish_completion.install "completions/indev.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/intility/indev/releases/download/v0.4.0/indev_darwin_arm64.tar.gz",
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["DOWNLOADER_GITHUB_TOKEN"]}"
        ]
      sha256 "2197ebc8d60dc418a781999ecc1b179a0b34343d566eacc12bad4c6b4430c2de"

      def install
        bin.install "indev"
        bash_completion.install "completions/indev.bash" => "indev"
        zsh_completion.install "completions/indev.zsh" => "_indev"
        fish_completion.install "completions/indev.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/intility/indev/releases/download/v0.4.0/indev_linux_x86_64.tar.gz",
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["DOWNLOADER_GITHUB_TOKEN"]}"
        ]
      sha256 "3fe894510b2328c633d1d8dc329c618176e9dc15ea693718c3dba2fa1a47d1fa"
      def install
        bin.install "indev"
        bash_completion.install "completions/indev.bash" => "indev"
        zsh_completion.install "completions/indev.zsh" => "_indev"
        fish_completion.install "completions/indev.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/intility/indev/releases/download/v0.4.0/indev_linux_arm64.tar.gz",
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["DOWNLOADER_GITHUB_TOKEN"]}"
        ]
      sha256 "6c970b76eedb52f82924158f130573e7db175640845d7f1c8db2993018804296"
      def install
        bin.install "indev"
        bash_completion.install "completions/indev.bash" => "indev"
        zsh_completion.install "completions/indev.zsh" => "_indev"
        fish_completion.install "completions/indev.fish"
      end
    end
  end
end
